version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            -   app
        container_name: nginx
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   mysql_container
        container_name: app

    mysql_container:
        image: mysql:8.0
        restart: always
        volumes:
            -   ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: tz_laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            -   "8101:3306"
        command:
            --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        container_name: mysql_container
